name       : graphene
version    : 1.10.2
release    : 2
source     :
    - https://github.com/ebassi/graphene/releases/download/1.10.2/graphene-1.10.2.tar.xz : e97de8208f1aac4f913d4fa71ab73a7034e807186feb2abe55876e51c425a7f6
license    : MIT
component  : desktop.gnome
avx2       : yes
summary    : A thin layer of types for graphic libraries
description: |
    A thin layer of types for graphic libraries
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
setup      : |
    %meson_configure -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
