name       : graphene
version    : 1.10.0
release    : 1
source     :
    - https://github.com/ebassi/graphene/releases/download/1.10.0/graphene-1.10.0.tar.xz : 406d97f51dd4ca61e91f84666a00c3e976d3e667cd248b76d92fdb35ce876499
license    : MIT
component  : desktop.gnome
avx2       : yes
summary    : A thin layer of types for graphic libraries
description: |
    A thin layer of types for graphic libraries
builddeps  :
    - pkgconfig(gobject-introspection-1.0)
setup      : |
    %meson_configure -Dinstalled_tests=false
build      : |
    %ninja_build
install    : |
    %ninja_install
